version: 2
updates:
  # NPM

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    groups:
      postcss:
        patterns:
          - "postcss*"
      babel:
        patterns:
          - "babel*"
          - "@babel/*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
    versioning-strategy: increase
    open-pull-requests-limit: 20

  # GitHub Actions

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
