name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Node setup
        uses: ./.github/actions/node-setup

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Node setup
        uses: ./.github/actions/node-setup

      - name: Build CommonJS for tests
        run: npm run build:cjs

      - name: Run test
        run: npm run test
